apiVersion: v1
kind: ServiceAccount
metadata:
  name: minikura-dev
  namespace: minikura
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minikura-dev-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["minikura.kirameki.cafe"]
    resources: ["minecraftservers", "reverseproxyservers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minikura-dev-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minikura-dev-role
subjects:
  - kind: ServiceAccount
    name: minikura-dev
    namespace: minikura
---
apiVersion: v1
kind: Secret
metadata:
  name: minikura-dev-token
  namespace: minikura
  annotations:
    kubernetes.io/service-account.name: minikura-dev
type: kubernetes.io/service-account-token
