apiVersion: v1
kind: ServiceAccount
metadata:
  name: minikura-operator
  namespace: minikura
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minikura-operator-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "persistentvolumeclaims", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["minikura.kirameki.cafe"]
    resources: ["minecraftservers", "reverseproxyservers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minikura-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minikura-operator-role
subjects:
  - kind: ServiceAccount
    name: minikura-operator
    namespace: minikura
---
# Secret to hold the service account token
apiVersion: v1
kind: Secret
metadata:
  name: minikura-operator-token
  namespace: minikura
  annotations:
    kubernetes.io/service-account.name: minikura-operator
type: kubernetes.io/service-account-token
